name: release
on:
  push:
    branches:
      - main
      - develop/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop/*

jobs:


  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20

      - name: Go mod tidy
        run: |
          set -e
          go mod tidy

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64   go build -o ./bin/doraemon-linux-x86_64  .
          GOOS=linux GOARCH=arm64   go build -o ./bin/doraemon-linux-aarch64 .
          GOOS=linux GOARCH=riscv64 go build -o ./bin/doraemon-linux-riscv64 .
          GOOS=linux GOARCH=s390x   go build -o ./bin/doraemon-linux-s390x   .


  publish:
    if: github.ref_type == 'tag'
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v3

      - name: GitHub Release
        uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37 # v1.10.0
        with:
          artifacts: ./bin/*
          generateReleaseNotes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
